### ISSUE TITLE
Copy isn't working

### ISSUE THREAD

**Issue by grallm** [grallm/m1-multicore-programming#4]
```
TL2.AbortException: Copied date is after transaction birth date
	at TL2.RegisterTL2.read(RegisterTL2.java:88)
	at TL2.RegisterTL2.read(RegisterTL2.java:60)
	at tp3.Dictionary$Node.add(Dictionary.java:102)
	at tp3.Dictionary.add(Dictionary.java:128)
	at Main.main(Main.java:29)
```

`Register` has a date after the `Transaction`

This may be because
- we are not finding the local copies in the `Transaction` when `X.read`
- another transaction committed, but means `Transaction` isn't restarting

**Comment by grallm** [comment]
Problem changed
```
TL2.AbortException: Copied date is after transaction birth date
	at TL2.RegisterTL2.read(RegisterTL2.java:77)
	at TL2.RegisterTL2.read(RegisterTL2.java:61)
	at tp3.Dictionary$Node.add(Dictionary.java:76)
	at tp3.Dictionary$Node.add(Dictionary.java:80)
	at tp3.Dictionary$Node.add(Dictionary.java:80)
	at tp3.Dictionary$Node.add(Dictionary.java:80)
	at tp3.Dictionary$Node.add(Dictionary.java:90)
	at tp3.Dictionary.add(Dictionary.java:112)
	at Main.main(Main.java:30)
```
